spring.application.name=layers

# Render asigna el puerto mediante la variable PORT
server.port=${PORT:8080}

# Configuración de H2 guardando en archivo local temporal del contenedor
spring.datasource.url=jdbc:h2:mem:categoriasdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Deshabilitar consola H2 en producción (por seguridad)
spring.h2.console.enabled=false

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
